const en = {
    btc: "BTC",
    bitcoin: "Bitcoin",
    settings: "Settings",
    general: "General",
    referenceExhangeRate: "Reference Exchange Rate",
    about: "About",
    version: "Version",
    priceHistory: "Price History",
    currentPrice: "Current Price",
    balance: "Balance",
    in: "in",
    priceErrorMessage: "Could not get price for",
    priceHistoryErrorMessage: "Could not get price history for",
    priceObtainedFrom: "Prices are obtained from",
    lastUpdatedAt: "Last Updated: Today at",
    wallets: "Wallets",
    noWalletText: "No wallets has been added. Please click plus icon to add new wallet.",
    addWalletHeader: "Bitcoin Wallet:",
    addWalletHeader1: "Simple and Secure",
    addWalletSubHeader: "We'll get you set up in no time. Select your preferrable wallet!",
    importScreenHeaderText: "Please enter your public key, xpub and app will do its best to guess the correct format and import your wallet.",
    importWallet: 'Import Wallet',
    scanQRCode: 'Scan QR Code',
    scanQRCodeTopContentMessage: 'Please move your camera over the QR code',
    scan: 'Scan',
    watchOnly: 'Imported Watch-Only',
    transactions: 'Transactions'
}

export default en;