const en = {
    btc: "BTC",
    bitcoin: "Bitcoin",
    settings: "Settings",
    general: "General",
    referenceExhangeRate: "Reference Exchange Rate",
    about: "About",
    version: "Version",
    priceHistory: "Price History",
    currentPrice: "Current Price",
    balance: "Balance",
    in: "in",
    priceErrorMessage: "Could not get price for",
    priceHistoryErrorMessage: "Could not get price history for",
    priceObtainedFrom: "Prices are obtained from",
    lastUpdatedAt: "Last Updated: Today at",
    wallets: "Wallets",
    noWalletText: "No wallets has been added. Please click + icon to add new wallet.",
    addWalletHeader: "Bitcoin Wallet:",
    addWalletHeader1: "Simple and Secure",
    addWalletSubHeader: "We'll get you set up in no time. Select your preferrable wallet!",
    importScreenHeaderText: "Please enter your public key(xpub), and app will do its best to guess the correct format and import your wallet.",
    importScreenHeaderTextTestnet: "Please enter your public key(tpub), and app will do its best to guess the correct format and import your wallet.",
    importWallet: 'Import Wallet',
    scanQRCode: 'Scan QR Code',
    scanQRCodeTopContentMessage: 'Please move your camera over the QR code',
    scan: 'Scan',
    watchOnly: 'Imported Watch-Only',
    transactions: 'Transactions',
    ago: 'ago',
    noTransactionsText: 'Your transactions will be shown here.',
    invalidPubKey: 'Invalid public key. Please enter valid public key.',
    updating: 'Updating',
    wallet: 'Wallet',
    name: 'Name',
    type: 'Type',
    transactionsCount: 'Transactions Count',
    derivationPath: 'Derivation Path',
    transaction: 'Transaction',
    sent: 'Sent',
    received: 'Received',
    on: 'on',
    completed: 'Completed',
    unconfirmed: 'Unconfirmed',
    pendingConfirmation: 'Pending Confirmation',
    transactionDetails: 'Transaction Details',
    confirmations: 'Confirmations',
    transactionId: 'Transaction Id',
    copiedToClipboard: 'Copied to clipboard',
    warning: 'Warning!',
    warningTestnetText: 'This wallet operates on a test network. Anything you receive or send here has no value.',
    saved: 'Saved',
    invalidPublicKey: 'Network operates on testnet network. Please enter valid testnet public key.',
    bitcoinDenomination: 'Bitcoin denomination',
    close: 'Close',
    import: 'Import',
    watchOnlyButtonTitle: 'Watch-Only',
    sats: 'sats',
    bits: 'bits',
    mBtc: 'mBTC',
    walletExistMessage: 'Wallet already exist with same public key. Please enter different public key',
    totalBalance: 'Total Balance',
    testnet: 'Testnet',
    send: 'Send',
    receive: 'Receive',
    share: 'Share',
    address: 'Address',
    noConnection: 'No internet connection',
    showPriceCard: 'Show price widget',
    touchId: 'Touch Id',
    biometrics: 'Biometrics',
    security: 'Security',
    biometricsNotSupported: 'Biometrics support not available on this device',
    confirmIdentityMessage: 'Please confirm your identity',
    newWallet: 'New Wallet',
    selectWallet: 'Select Wallet',
    singlesig: 'Singlesig',
    singlesigDescription: 'Your funds are secured by a single key held on your device. Simpler to set up and use.',
    selectWalletType: 'Select wallet type',
    hdSegwitBech32: 'Segwit (BIP84 Bech 32 native)',
    hdSegwitP2SH: 'Segwit (BIP49 P2SH)',
    hdLegacyP2PKH: 'Legacy (BIP44 P2PKH)',
    walletType: 'Wallet Type',
    recoveryPhraseLength: 'Recovery phrase length',
    continue: 'Continue',
    wallet1: 'Wallet 1',
    writeDownTheWords: 'Write down the words',
    writeDownThePhrase: 'Write down your recovery phrase on paper and store it somewhere safe.',
    create: 'Create',
    next: 'Next',
    success: 'Success',
    electrumOfflineMessage: 'Electrum server is offline. Please try again later.',
    status: 'Status',
    electrumServer: 'Electrum Server',
    connected: 'Connected',
    notConnected: 'Not conneted',
    networkStatus: 'Network status',
    delete: 'Delete',
    deletePrompt: 'Are you sure you want to delete the wallet?',
    yes: 'Yes',
    cancel: 'Cancel',
    ok: 'Ok',
    segwit: 'Segwit',
    segwitP2SH: 'SegwitP2SH',
    legacy: 'Legacy',
    sendTo: 'Send To',
    max: 'Max',
    availableBalance: 'Available balance',
    fee: 'Fee',
    enterAddress: 'Enter Address',
    recipient: 'Recipient',
    testnetWalletSupportMessage: 'Testnet import only support BIP84 Bech 32 native wallet public key(tpub). Other wallet types may produce inaccurate data.',
    save: 'Save',
    insufficientFunds: 'Insufficient funds',
    invalidAddress: 'Invalid address',
    review: 'Review',
    invalidAmount: 'Invalid amount',
    custom: 'Custom',
    low: 'Low',
    medium: 'Medium',
    fast: 'Fast',
    confirmationTime: 'Confirmation time',
    hours: 'hours',
    minutes: 'minutes',
    fetchingFeeMessage: 'Fetching mempool fee..',
    fetchingAddressMessage: 'Fetching address..',
    fetchingUtxoMessage: 'Fetching utxo..',
    creatingTransactionMessage: 'Creating transaction..',
    broadcastTransactionMessage: 'Broadcasting transaction..',
    addedToNotificationQueue: 'Adding to notification queue..',
    creatingWalletMessage: 'Creating wallet..',
    savingToDiskMessage: 'Saving to disk..',
    deleteWalletMessage: 'Deleting wallet..',
    importWalletMessage: 'Importing wallet..'
}

export default en;